name: test-and-publish
on:
    - push
jobs:
    test-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.10
            - run: npm ci
            - run: npm run bootstrap
            - run: npm run check
            - name: canary publish
              run: ./node_modules/.bin/lerna publish --canary --yes
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
