name: test-and-publish
on:
    - push
jobs:
    test-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.10
            - run: npm ci
            - run: npm run bootstrap
            - run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}
            - run: lerna exec -- npm version $(node -p "require(\"./lerna.json\").version")-$GITHUB_SHA --git-tag-version false
            - run: lerna exec -- npm publish
